### ISSUE TITLE
Some warnings

### ISSUE THREAD

**Issue by averms** [raxod502/mla13#6]
I'm getting some warnings with TeX Live 2020. Wondering if they can be fixed?

```
Package Fancyhdr Warning: \headheight is too small (12.0pt): 
Make it at least 14.49998pt.
We now make it that large for the rest of the document.
This may cause the page layout to be inconsistent, however.
```
and
```
Package biblatex Warning: Macro 'cite:idem' already defined.
(biblatex)                Using \renewbibmacro on input line 281.


Package biblatex Warning: Macro 'cite:mla:title:internal' already defined.
(biblatex)                Using \renewbibmacro on input line 287.


Package biblatex Warning: Macro 'cite:mla:title' already defined.
(biblatex)                Using \renewbibmacro on input line 302.
```

**Comment by raxod502** [comment]
Most likely they could be. I'd be happy to receive a pull request. Otherwise, the problem will likely not be solved anytime soon since I am graduating college and hope to never see MLA format again :P

**Comment by averms** [comment]
Haha just starting college. Will have to deal with MLA for a few more years. Anyway, my solution would be to remove the code that does the biblatex stuff since I think biblatex-mla does everything I need (idem is removed from newer versions of MLA, title citing is done automatically). As for the fancyhdr issue, I have no clue.

If you want me to submit a pull request deleting the biblatex macros let me know.

**Comment by raxod502** [comment]
If biblatex-mla has been updated to handle everything properly, then I see no reason not to remove the code from here. If you submit a pull request I can test with one of my existing documents to see if anything changes.

**Comment by averms** [comment]
It looks like biblatex-mla hasn't been updated since 2016, so I doubt whatever the problem was has been fixed
